#! /bin/bash

# bash-session
# bash session management functions.

# Copyright (C) 2017 Stephen L Jones <sljones@slohj.org>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# TODO:
#
# ! Move session title stuff here.
#   Prompt string ???
#
# ! save and set session dependent histories.
#
# ! set directory stack on session start.
#
# ! Use trap EXIT to save all session info.
#
# ! history stuff.
#
# * Look into overloading the builtin help to provide help information for user
#   functions and aliases.
#

# Global variables
declare -g _bs_name

# Public functions

# Display current session name and/or saved session names or set the current
# session name, loading the session if it already had been saved.
bsess ()
{
    # Error check, there should be onle 0 or one parameters.
    if [[ -n "${2}" ]]
    then
        # FIXME:
        # Error message needed: bad usage!
        return 1
    fi

    if [[ -z "${1}" ]]
    then
        # Print the current session if it has already been set.
        if [[ -n "${_bs_name}" ]]
        then
            printf 'Current session: %s\n\n' "${_bs_name}"
        fi

        # Save the current state of nullglob.
        globsetting="$(shopt -p nullglob)"
        shopt -s nullglob

        # Display list of avialable sessions.
        for file_session in ~/.bash_session_*
        do
            session="${file_session#.bash_session_}"
            printf 'Saved sessions:\n'
            printf '\t%s\n' "${session}"
        done

        # Restore the original state of nullglob.
        ${globsetting}
    else
        _bs_name="${1}"
        # Source the session file if it exists.
        if [[ -f "~/.bash_session_${_bs_name}" ]]
        then
            . "~/.bash_session_${_bs_name}"
        fi
    fi
}

# Print the dirstack to stdout in a reusabe format.
printd ()
{
    local ind

    for (( ind = -1 ; ind >= 0 - ${#DIRSTACK[@]} ; ind-- ))
    do
        # FIXME:
        # bash currently does not properly expand the ~ in the array.
        # This has been fixed in bash development but has not been released as
        # an offical patch yet, so we need to still use the string replacement.
        #printf "pushd -n %q > /dev/null\n" "${DIRSTACK[${ind}]}"
        printf "pushd -n %q > /dev/null\n" "${DIRSTACK[${ind}]/#\~/${HOME}}"
    done
}

# Private functions

# This function is used by PROMPT_COMMAND to set both the command line prompt
# and the xterm title.
_bs_set_stitle ()
{
    if [[ -n ${_bs_name} ]]
    then
        stitle="${_bs_name} "
        if [[ -v DISPLAY ]]
        then
            echo -ne "\033]0;${_bs_name}\007"
        fi
    else
        stitle=""
    fi
}

# Execute on load commands

# Set PROMPT_COMMAND
if [[ -v PROMPT_COMMAND ]]
then
    # The user is already using PROMPT_COMMAND for something else, so just turn
    # it into a compound command.
    PROMPT_COMMAND="${PROMPT_COMMAND}; _bs_set_stitle"
else
    PROMPT_COMMAND="_bs_set_stitle"
fi

# Vim mode line {{{1
# vim: expandtab softtabstop=4 shiftwidth=4 filetype=sh:
